{
 "title": "Log Anomaly Detector -  Customer Dashboard",
 "description": "Provides anomaly detection of logs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "label_values(aiops_lad_loglines_count, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Log Entries Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_loglines_count{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Percentage of non anomalous logs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"0\", job=\"$job\"} / aiops_lad_anomaly_count{job=\"$job\"}\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Anomaly",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"1\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Anomaly vs Regular Logs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"0\",job=\"$job\"}\n",
     "legendFormat": "Normal Log"
    },
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"1\",job=\"$job\"}",
     "legendFormat": "Anomaly Log"
    }
   ]
  },
  {
   "title": "Rate Anomalies per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aiops_lad_anomaly_count{anomaly_status=\"0\",job=\"$job\"}[1m])",
     "legendFormat": "normal"
    },
    {
     "expr": "rate(aiops_lad_anomaly_count{anomaly_status=\"1\",job=\"$job\"}[1m])",
     "legendFormat": "anomaly"
    }
   ]
  },
  {
   "title": "Total Training Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_train_count_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Feedback Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_human_feedback_count_total{anomaly_status=\"False\",job=\"$job\"}",
     "legendFormat": "{{Feedback count}}"
    }
   ]
  },
  {
   "title": "Total Inference Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_inference_count_total{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Anomaly Score",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aiops_lad_anomaly_avg_score{job=\"$job\"}",
     "legendFormat": "Average Anomaly Score"
    },
    {
     "expr": "aiops_lad_threshold{job=\"$job\"}",
     "legendFormat": "Threshold"
    }
   ]
  },
  {
   "title": "False Positive Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "increase(aiops_lad_inference_count_total{job=\"$job\"}[8h])",
     "legendFormat": "False positives found in last 8 hours"
    }
   ]
  },
  {
   "title": "Threshold Value",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_threshold{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Rate in last 5 mins of logs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aiops_lad_loglines_count[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of log lines processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"1\",job=\"$job\"}\n",
     "legendFormat": "Anomaly Log"
    },
    {
     "expr": "aiops_lad_anomaly_count{job=\"$job\"}\n",
     "legendFormat": "Normal log"
    }
   ]
  },
  {
   "title": "Number of log lines ingested",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aiops_lad_loglines_count", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}